python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Amb.faa ../../15_orthofinder_seq/Proteome/Amb.cds.fas 1 ../Orthogroups.Sapria.functional.list Amb
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Cin.faa ../../15_orthofinder_seq/Proteome/Cin.cds.fas 28 ../Orthogroups.Sapria.functional.list Cin
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Osa.faa ../../15_orthofinder_seq/Proteome/Osa.cds.fas 25 ../Orthogroups.Sapria.functional.list Osa
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Sor.faa ../../15_orthofinder_seq/Proteome/Sor.cds.fas 34 ../Orthogroups.Sapria.functional.list Sor
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Aqu.faa ../../15_orthofinder_seq/Proteome/Aqu.cds.fas 2 ../Orthogroups.Sapria.functional.list Aqu
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Nel.faa ../../15_orthofinder_seq/Proteome/Nel.cds.fas 24 ../Orthogroups.Sapria.functional.list Nel
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Dau.faa ../../15_orthofinder_seq/Proteome/Dau.cds.fas 6 ../Orthogroups.Sapria.functional.list Dau
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Hel.faa ../../15_orthofinder_seq/Proteome/Hel.cds.fas 9 ../Orthogroups.Sapria.functional.list Hel
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Ath.faa ../../15_orthofinder_seq/Proteome/Ath.cds.fas 3 ../Orthogroups.Sapria.functional.list Ath
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Cit.faa ../../15_orthofinder_seq/Proteome/Cit.cds.fas 4 ../Orthogroups.Sapria.functional.list Cit
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Cof.faa ../../15_orthofinder_seq/Proteome/Cof.cds.fas 5 ../Orthogroups.Sapria.functional.list Cof
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Gly.faa ../../15_orthofinder_seq/Proteome/Gly.cds.fas 7 ../Orthogroups.Sapria.functional.list Gly
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Han.faa ../../15_orthofinder_seq/Proteome/Han.cds.fas 8 ../Orthogroups.Sapria.functional.list Han
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Ipo.faa ../../15_orthofinder_seq/Proteome/Ipo.cds.fas 10 ../Orthogroups.Sapria.functional.list Ipo
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Jat.faa ../../15_orthofinder_seq/Proteome/Jat.cds.fas 11 ../Orthogroups.Sapria.functional.list Jat
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Mes.faa ../../15_orthofinder_seq/Proteome/Mes.cds.fas 12 ../Orthogroups.Sapria.functional.list Mes
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Mim.faa ../../15_orthofinder_seq/Proteome/Mim.cds.fas 13 ../Orthogroups.Sapria.functional.list Mim
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Nic.faa ../../15_orthofinder_seq/Proteome/Nic.cds.fas 14 ../Orthogroups.Sapria.functional.list Nic
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Ole.faa ../../15_orthofinder_seq/Proteome/Ole.cds.fas 15 ../Orthogroups.Sapria.functional.list Ole
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Pht.faa ../../15_orthofinder_seq/Proteome/Pht.cds.fas 16 ../Orthogroups.Sapria.functional.list Pht
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Pru.faa ../../15_orthofinder_seq/Proteome/Pru.cds.fas 17 ../Orthogroups.Sapria.functional.list Pru
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Ptr.faa ../../15_orthofinder_seq/Proteome/Ptr.cds.fas 18 ../Orthogroups.Sapria.functional.list Ptr
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Ses.faa ../../15_orthofinder_seq/Proteome/Ses.cds.fas 19 ../Orthogroups.Sapria.functional.list Ses
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Sol.faa ../../15_orthofinder_seq/Proteome/Sol.cds.fas 20 ../Orthogroups.Sapria.functional.list Sol
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Str.faa ../../15_orthofinder_seq/Proteome/Str.cds.fas 21 ../Orthogroups.Sapria.functional.list Str
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Vvi.faa ../../15_orthofinder_seq/Proteome/Vvi.cds.fas 22 ../Orthogroups.Sapria.functional.list Vvi
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Cus.faa ../../15_orthofinder_seq/Proteome/Cus.cds.fas 23 ../Orthogroups.Sapria.functional.list Cus
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Act.faa ../../15_orthofinder_seq/Proteome/Act.cds.fas 26 ../Orthogroups.Sapria.functional.list Act
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Gos.faa ../../15_orthofinder_seq/Proteome/Gos.cds.fas 27 ../Orthogroups.Sapria.functional.list Gos
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Cpa.faa ../../15_orthofinder_seq/Proteome/Cpa.cds.fas 29 ../Orthogroups.Sapria.functional.list Cpa
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Med.faa ../../15_orthofinder_seq/Proteome/Med.cds.fas 30 ../Orthogroups.Sapria.functional.list Med
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Rca.faa ../../15_orthofinder_seq/Proteome/Rca.cds.fas 31 ../Orthogroups.Sapria.functional.list Rca
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Rhi.faa ../../15_orthofinder_seq/Proteome/Rhi.cds.fas 32 ../Orthogroups.Sapria.functional.list Rhi
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Rtu.faa ../../15_orthofinder_seq/Proteome/Rtu.cds.fas 33 ../Orthogroups.Sapria.functional.list Rtu
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Tca.faa ../../15_orthofinder_seq/Proteome/Tca.cds.fas 35 ../Orthogroups.Sapria.functional.list Tca
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Tet.faa ../../15_orthofinder_seq/Proteome/Tet.cds.fas 36 ../Orthogroups.Sapria.functional.list Tet
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Vac.faa ../../15_orthofinder_seq/Proteome/Vac.cds.fas 37 ../Orthogroups.Sapria.functional.list Vac
python extract_gen_fam_seq.py Orthogroups.10sp.onemalp.raff.csv ../../15_orthofinder_seq/Proteome/Shi.faa ../../15_orthofinder_seq/Proteome/Shi.cds.fas 38 ../Orthogroups.Sapria.functional.list Sap

